// Generated by CoffeeScript 1.7.1
(function() {
  var checkHash, currentHash;

  currentHash = null;

  checkHash = function() {
    var hash, installButton;
    hash = location.hash;
    if (hash === currentHash) {
      return;
    }
    currentHash = hash;
    if (currentHash.indexOf('package/') !== -1) {
      installButton = $('.installbutton');
      installButton.text('Add to ProxMate');
      installButton.addClass('pxm-connected');
      installButton.attr('a', '');
      return installButton.mouseup(function() {
        var packageid;
        packageid = installButton.attr('packageid');
        return window.open(chrome.extension.getURL("pages/install/index.html#!/install/" + packageid));
      });
    }
  };

  setInterval(checkHash, 1000);

}).call(this);
