// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  describe('Controller: InstallCtrl', function() {
    var MainCtrl, scope;
    beforeEach(module('proxmateApp'));
    MainCtrl = {};
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      var InstallCtrl;
      scope = $rootScope.$new();
      return InstallCtrl = $controller('InstallCtrl', {
        $scope: scope
      });
    }));
    return it('should attach a list of awesomeThings to the scope', function() {
      return expect(scope.asdf).toBe(123);
    });
  });

}).call(this);
