// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  describe('Controller: InstallCtrl', function() {
    var MainCtrl, controller, scope;
    beforeEach(module('proxmateApp'));
    MainCtrl = {};
    scope = {};
    controller = {};
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return controller = $controller;
    }));
    return it('should call installPackage and indicate the status', function() {
      var InstallCtrl, chromeSpy;
      chromeSpy = jasmine.createSpyObj('chrome', ['installPackage']);
      chromeSpy.installPackage.andCallFake(function(config, callback) {
        return callback({
          success: true
        });
      });
      InstallCtrl = controller('InstallCtrl', {
        $scope: scope,
        $routeParams: {
          'packageId': 123
        },
        Chrome: chromeSpy
      });
      expect(scope.status).toBe('Installed successfully!');
      return expect(chromeSpy.installPackage).toHaveBeenCalledWith(123, jasmine.any(Function));
    });
  });

}).call(this);
