// Generated by CoffeeScript 1.7.1
(function() {
  var file, tests, _i, _len, _ref;

  tests = [];

  _ref = Object.keys(window.__karma__.files);
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    file = _ref[_i];
    if (/test\.js$/.test(file)) {
      tests.push(file);
    }
  }

  window.chrome = {
    storage: {
      local: {
        set: function() {},
        get: function() {}
      }
    },
    proxy: {
      settings: {
        set: function() {},
        clear: function() {}
      }
    }
  };

  require.config({
    baseUrl: '/base/src/js',
    paths: {
      "text": "../../bower_components/requirejs-text/text",
      "jquery": "../../bower_components/jquery/jquery"
    },
    deps: tests,
    callback: window.__karma__.start
  });

}).call(this);
