// Generated by CoffeeScript 1.7.1
(function() {
  define(['runtime', 'package-manager', 'server-manager', 'proxy-manager'], function(Runtime, PackageManager, ServerManager, ProxyManager) {
    return describe('Runtime ', function() {
      beforeEach(function() {
        return this.sandbox = sinon.sandbox.create();
      });
      afterEach(function() {
        return this.sandbox.restore();
      });
      return describe('start', function() {
        it('should do nothing if no servers or packages are available', function() {
          var generatePacStub, getInstalledPackagesStub, getServersStub, setPacStub;
          getInstalledPackagesStub = this.sandbox.stub(PackageManager, 'getInstalledPackages', function() {
            return [];
          });
          getServersStub = this.sandbox.stub(ServerManager, 'getServers', function() {
            return [];
          });
          generatePacStub = this.sandbox.stub(ProxyManager, 'generateProxyAutoconfigScript');
          setPacStub = this.sandbox.stub(ProxyManager, 'setProxyAutoconfig');
          Runtime.start();
          assert.isTrue(getInstalledPackagesStub.calledOnce);
          assert.isTrue(getServersStub.calledOnce);
          assert.isFalse(generatePacStub.calledOnce);
          return assert.isFalse(setPacStub.calledOnce);
        });
        return it('should generate and set pac if packages and servers are available', function() {
          var generatePacStub, getInstalledPackagesStub, getServersStub, setPacStub;
          getInstalledPackagesStub = this.sandbox.stub(PackageManager, 'getInstalledPackages', function() {
            return [1];
          });
          getServersStub = this.sandbox.stub(ServerManager, 'getServers', function() {
            return [1, 2, 3];
          });
          generatePacStub = this.sandbox.stub(ProxyManager, 'generateProxyAutoconfigScript');
          setPacStub = this.sandbox.stub(ProxyManager, 'setProxyAutoconfig');
          Runtime.start();
          assert.isTrue(getInstalledPackagesStub.calledOnce);
          assert.isTrue(getServersStub.calledOnce);
          assert.isTrue(generatePacStub.calledOnce);
          return assert.isTrue(setPacStub.calledOnce);
        });
      });
    });
  });

}).call(this);
