// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  describe('Factory: chrome', function() {
    var chrome, runtimeSpy;
    beforeEach(module('proxmateApp'));
    runtimeSpy = jasmine.createSpyObj('runtime', ['sendMessage']);
    runtimeSpy.sendMessage.andCallFake(function(config, callback) {
      return callback('some callback string');
    });
    window.chrome = {
      runtime: runtimeSpy
    };
    chrome = {};
    beforeEach(inject(function(_chrome_) {
      return chrome = _chrome_;
    }));
    return it('should be an object', function() {
      var callback;
      callback = jasmine.createSpy('callback spy');
      chrome.installPackage(123, callback);
      expect(runtimeSpy.sendMessage).toHaveBeenCalledWith({
        action: 'installPackage',
        params: {
          packageId: 123
        }
      }, jasmine.any(Function));
      return expect(callback).toHaveBeenCalledWith('some callback string');
    });
  });

}).call(this);
