// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    paths: {
      "text": "../../bower_components/requirejs-text/text",
      "jquery": "../../bower_components/jquery/jquery"
    }
  });

  (function() {
    return require(['config', 'package-manager', 'storage', 'proxy-manager'], function(Config, PackageManager, Storage, ProxyManager) {
      Config.init();
      Storage.init();
      PackageManager.init();
      return ProxyManager.init();
    });
  })();

}).call(this);
