// Generated by CoffeeScript 1.7.1
(function() {
  require.config({
    paths: {
      "text": "../../bower_components/requirejs-text/text",
      "jquery": "../../bower_components/jquery/dist/jquery"
    }
  });

  (function() {
    return require(['config', 'package-manager', 'storage', 'proxy-manager', 'server-manager', 'event-binder', 'runtime'], function(Config, PackageManager, Storage, ProxyManager, ServerManager, EventBinder, Runtime) {
      Config.init();
      return Storage.init(function() {
        return ServerManager.init(function() {
          PackageManager.init();
          ProxyManager.init();
          EventBinder.init();
          Runtime.init();
          return Runtime.start();
        });
      });
    });
  })();

}).call(this);
