// Generated by CoffeeScript 1.7.1
(function() {
  define(['chrome', 'package-manager'], function(Chrome, PackageManager) {
    var exports, init, messageListener;
    init = function() {
      return Chrome.runtime.onMessage.addListener(exports.messageListener);
    };
    messageListener = function(request, sender, sendResponse) {
      var params;
      params = request.params;
      switch (request.action) {
        case 'installPackage':
          PackageManager.installPackage(params.packageId, function(response) {
            return sendResponse(response);
          });
      }
      return true;
    };
    exports = {
      init: init,
      messageListener: messageListener
    };
    return exports;
  });

}).call(this);
