// Generated by CoffeeScript 1.7.1
(function() {
  define(['chrome', 'package-manager'], function(Chrome, PackageManager) {
    var exports, init, messageListener;
    init = function() {
      return Chrome.runtime.onMessage.addListener(exports.messageListener);
    };

    /**
     * Event listener for chrome message events
     * @param  {Object} request      request and parameters
     * @param  {Object} sender       sender object
     * @param  {Function} sendResponse callback to emit answer back to frontend
     * @return {boolean}              status whether to keep the connection open or not
     */
    messageListener = function(request, sender, sendResponse) {
      var params;
      params = request.params;
      switch (request.action) {
        case 'installPackage':
          PackageManager.installPackage(params.packageId, function(response) {
            return sendResponse(response);
          });
      }
      return true;
    };
    exports = {
      init: init,
      messageListener: messageListener
    };
    return exports;
  });

}).call(this);
