// Generated by CoffeeScript 1.7.1
(function() {
  define(['package-manager', 'server-manager', 'proxy-manager', 'storage'], function(PackageManager, ServerManager, ProxyManager, Storage) {
    var exports, init, restart, start, stop;
    init = function() {};

    /**
     * Starts the app. Retrieves servers and sets pac
     */
    start = function() {
      var globalStatus, pac, packages, servers;
      globalStatus = Storage.get('global_status');
      if (!globalStatus) {
        exports.stop();
        return;
      }
      packages = PackageManager.getInstalledPackages();
      servers = ServerManager.getServers();
      if (packages.length === 0 || servers.length === 0) {
        return console.info('No servers and packages');
      } else {
        pac = ProxyManager.generateProxyAutoconfigScript(packages, servers);
        return ProxyManager.setProxyAutoconfig(pac);
      }
    };

    /**
     * Restarts application flow. This means the app is already running and now getting started again.
     */
    restart = function() {
      return exports.start();
    };

    /**
     * Removed the proxy from chrome
     */
    stop = function() {
      return ProxyManager.clearProxy();
    };
    exports = {
      init: init,
      start: start,
      restart: restart,
      stop: stop
    };
    return exports;
  });

}).call(this);
