// Generated by CoffeeScript 1.7.1
(function() {
  define(['package-manager', 'server-manager', 'proxy-manager'], function(PackageManager, ServerManager, ProxyManager) {
    var exports, init, start;
    init = function() {};

    /**
     * Starts the app. Retrieves servers and sets pac
     */
    start = function() {
      var pac, packages, servers;
      packages = PackageManager.getInstalledPackages();
      servers = ServerManager.getServers();
      if (packages.length === 0 || servers.length === 0) {
        return console.info('No servers and packages');
      } else {
        pac = ProxyManager.generateProxyAutoconfigScript(packages, servers);
        return ProxyManager.setProxyAutoconfig(pac);
      }
    };
    exports = {
      init: init,
      start: start
    };
    return exports;
  });

}).call(this);
