// Generated by CoffeeScript 1.7.1
(function() {
  define(['storage'], function(Storage) {
    var exports, fetchServerList, init, loadServersFromStorage, servers;
    servers = [];
    init = function() {
      exports.loadServersFromStorage();
      return exports.fetchServerList();
    };

    /**
     * Load servers from storage into array
     */
    loadServersFromStorage = function() {
      return servers = Storage.get('server_config');
    };
    fetchServerList = function() {};
    exports = {
      init: init,
      loadServersFromStorage: loadServersFromStorage,
      fetchServerList: fetchServerList
    };
    return exports;
  });

}).call(this);
