// Generated by CoffeeScript 1.7.1
(function() {
  define(['chrome'], function(Chrome) {
    var copyFromChromeStorage, copyInterval, copyIntoChromeStorage, flush, get, init, internStorage, set;
    init = function(callback) {
      return copyFromChromeStorage(function() {
        var globalStatus;
        globalStatus = internStorage['global_status'];
        if (globalStatus == null) {
          internStorage['global_status'] = true;
        }
        return callback(internStorage);
      });
    };
    internStorage = {};
    copyInterval = null;

    /**
     * Writes the RAM storage into chrome HDD storage, after a 1 second delay
     */
    copyIntoChromeStorage = function() {
      clearInterval(copyInterval);
      return copyInterval = setTimeout(function() {
        return Chrome.storage.local.set(internStorage);
      }, 1000);
    };
    copyFromChromeStorage = function(callback) {
      return Chrome.storage.local.get(null, function(object) {
        internStorage = object;
        return callback();
      });
    };

    /**
     * Deletes all content from RAM storage
     */
    flush = function() {
      return internStorage = {};
    };

    /**
     * Returns value for 'key' from Storage
     * @return {String|Array} the value inside the storage
     */
    get = function(key) {
      return internStorage[key];
    };

    /**
     * Sets 'value' for 'key' in storage
     */
    set = function(key, value) {
      internStorage[key] = value;
      return copyIntoChromeStorage();
    };
    return {
      init: init,
      flush: flush,
      set: set,
      get: get
    };
  });

}).call(this);
