// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('popupApp', ['chrome']);

  angular.module('popupApp').controller('MainCtrl', [
    '$scope', 'Chrome', function($scope, Chrome) {
      $scope.updateProxmateStatus = function() {
        return Chrome.getProxmateStatus(function(response) {
          $scope.proxmateStatus = response;
          return $scope.$digest();
        });
      };
      $scope.updateProxmateStatus();
      $scope.deactivateProxmate = function() {
        return Chrome.setProxmateStatus(false, function() {
          return $scope.updateProxmateStatus();
        });
      };
      return $scope.activateProxmate = function() {
        return Chrome.setProxmateStatus(true, function() {
          return $scope.updateProxmateStatus();
        });
      };
    }
  ]);

}).call(this);
