// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('proxmateApp').factory('chrome', function() {
    return {
      installPackage: function(packageId, callback) {
        console.info("trying to install package " + packageId);
        return chrome.runtime.sendMessage({
          action: "installPackage",
          params: {
            packageId: packageId
          }
        }, function(response) {
          return callback(response);
        });
      }
    };
  });

}).call(this);
