// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('chrome', []).factory('Chrome', function() {
    return {
      installPackage: function(packageId, callback) {
        console.info("trying to install package " + packageId);
        return chrome.runtime.sendMessage({
          action: "installPackage",
          params: {
            packageId: packageId
          }
        }, function(response) {
          return callback(response);
        });
      },
      getProxmateStatus: function(callback) {
        return chrome.runtime.sendMessage({
          action: "getProxmateGlobalStatus",
          params: {}
        }, function(response) {
          return callback(response);
        });
      },
      setProxmateStatus: function(status, callback) {
        return chrome.runtime.sendMessage({
          action: "setProxmateGlobalStatus",
          params: {
            newStatus: status
          }
        }, function(response) {
          return callback(response);
        });
      }
    };
  });

}).call(this);
